"""Standalone end-to-end flight simulation example for Visual Object-Goal WAM.

Simulates a closed-loop drone visual approach toward a ground target (Red Truck),
complete with a tree occlusion event midway and final successful arrival.
"""
from __future__ import annotations

import os
import matplotlib.pyplot as plt
import numpy as np

from vgoal.detector import MockDetector
from vgoal.geometry import CameraIntrinsics, bbox_to_goal_rel, project_3d_to_pixel
from vgoal.tracker import TargetState, TargetTracker, TrackerConfig


def run_standalone_simulation():
    print("=====================================================================")
    print("🚀 Running Standalone Visual Object-Goal Closed-Loop Flight Demo")
    print("=====================================================================")

    # 1. Setup Camera Intrinsics (640x480, 80 deg horizontal FOV)
    cam = CameraIntrinsics.from_fov(fov_deg=80.0, width=640, height=480)
    tracker = TargetTracker(TrackerConfig(success_dist_m=3.0, max_occlusion_s=2.0))
    detector = MockDetector(class_name="red_truck")

    # 2. World setup: A stationary target (e.g. Red Truck) at World (25.0m, 4.0m, 0.0m)
    p_target_world = np.array([25.0, 4.0, 0.0], dtype=np.float32)

    # Drone initial state: starts at (0, 0, 0), facing +x (yaw = 0)
    drone_pos = np.array([0.0, 0.0, 0.0], dtype=np.float32)
    drone_yaw = 0.0  # rad

    dt = 0.2  # 5 Hz control cycle (0.2s per step)
    total_steps = 45

    # Telemetry logging
    log_time = []
    log_drone_x = []
    log_drone_y = []
    log_state = []
    log_goal_fwd = []
    log_goal_left = []
    log_goal_dist = []
    log_bbox_center_u = []
    log_bbox_center_v = []

    print(f"Target World Pos: {p_target_world}")
    print(f"Control Rate: {1.0/dt:.1f} Hz, Total Steps: {total_steps}\n")

    for step in range(total_steps):
        t = step * dt

        # -- Step A: Ground-truth relative position in drone body frame --
        delta_world = p_target_world - drone_pos
        c, s = np.cos(drone_yaw), np.sin(drone_yaw)
        gt_fwd = c * delta_world[0] + s * delta_world[1]
        gt_left = -s * delta_world[0] + c * delta_world[1]
        gt_up = delta_world[2]
        p_body_gt = np.array([gt_fwd, gt_left, gt_up], dtype=np.float32)
        true_dist = float(np.linalg.norm(p_body_gt))

        # -- Step B: Project 3D target into 2D camera image --
        u_px, v_px, depth_gt = project_3d_to_pixel(p_body_gt, cam)

        # Check if target is inside camera FOV [0, W] x [0, H]
        in_fov = (0 <= u_px < cam.width) and (0 <= v_px < cam.height) and (depth_gt > 0.5)

        # Simulate obstacle occlusion: steps 12 to 18 are blocked by a big tree
        is_occluded = (12 <= step <= 18)

        # -- Step C: Detector + Depth Head Simulation --
        if in_fov and not is_occluded:
            # 2D Bounding box around target (target size scales with 1/depth)
            box_w = max(20.0, 300.0 / max(depth_gt, 1.0))
            box_h = box_w * 0.8
            bbox = [u_px - box_w * 0.5, v_px - box_h * 0.5, u_px + box_w * 0.5, v_px + box_h * 0.5]
            detector.set_target(bbox, confidence=0.95)

            # Synthetic depth map generated by depth head (true depth + 2cm noise)
            depth_map = np.full((cam.height, cam.width), depth_gt + 0.02, dtype=np.float32)

            # Back-project 2D bbox + Depth Map -> 3D goal_rel
            det_result = detector.detect(np.zeros((cam.height, cam.width, 3), dtype=np.uint8))
            measured_goal_rel = bbox_to_goal_rel(det_result.bbox, depth_map, cam)
            det_conf = det_result.confidence
            bbox_u, bbox_v = u_px, v_px
        else:
            detector.set_target(None)
            measured_goal_rel = None
            det_conf = 0.0
            bbox_u, bbox_v = np.nan, np.nan

        # -- Step D: Simple proportional guidance policy using tracker's estimated goal --
        cur_goal = tracker.goal_rel
        if cur_goal is not None:
            # Heading error towards target in body frame
            heading_err = np.arctan2(cur_goal[1], cur_goal[0])
            dyaw_cmd = float(np.clip(heading_err * 0.4, -0.15, 0.15))
            fwd_cmd = float(np.clip(cur_goal[0] * 0.3, 0.2, 0.8))  # speed ~ 1~4 m/s
        else:
            # Search mode: gentle forward + rotate
            dyaw_cmd = 0.05
            fwd_cmd = 0.5

        # -- Step E: Update Spatial Tracker (with ego-motion dead reckoning) --
        state = tracker.update(
            measured_goal_rel,
            dt=dt,
            ego_delta_body=[fwd_cmd, 0.0, 0.0],
            ego_delta_yaw=dyaw_cmd,
            confidence=det_conf,
        )

        cur_goal_updated = tracker.goal_rel
        fwd_est = cur_goal_updated[0] if cur_goal_updated is not None else np.nan
        left_est = cur_goal_updated[1] if cur_goal_updated is not None else np.nan
        dist_est = cur_goal_updated[3] if cur_goal_updated is not None else np.nan

        tag = ""
        if is_occluded:
            tag = "🌲 [TREE OCCLUSION - Dead Reckoning Active]"
        elif state == TargetState.ARRIVED:
            tag = "🎯 [SUCCESS - Target Arrived!]"

        print(f"Step {step:02d} (t={t:.1f}s) | State: {state.value:<9} | "
              f"Est Goal: [Fwd: {fwd_est:5.1f}m, Left: {left_est:5.1f}m, Dist: {dist_est:5.1f}m] | "
              f"True Dist: {true_dist:5.1f}m {tag}")

        log_time.append(t)
        log_drone_x.append(drone_pos[0])
        log_drone_y.append(drone_pos[1])
        log_state.append(state.value)
        log_goal_fwd.append(fwd_est)
        log_goal_left.append(left_est)
        log_goal_dist.append(dist_est)
        log_bbox_center_u.append(bbox_u)
        log_bbox_center_v.append(bbox_v)

        # Update drone world pose for next step
        drone_pos[0] += c * fwd_cmd
        drone_pos[1] += s * fwd_cmd
        drone_yaw += dyaw_cmd

        if state == TargetState.ARRIVED and step > 5:
            print(f"\n✨ Drone arrived within 3.0m of target at step {step} (t={t:.1f}s, distance={dist_est:.2f}m)!")
            break

    # 3. Generate Visual Telemetry Plots
    fig, axs = plt.subplots(2, 2, figsize=(14, 10))
    fig.suptitle("Visual Object-Goal WAM (Method B) - Standalone Telemetry Demo", fontsize=14, fontweight="bold")

    # Plot 1: 2D Bird's Eye View Trajectory
    axs[0, 0].plot(log_drone_x, log_drone_y, "b-o", markersize=4, label="Drone Trajectory")
    axs[0, 0].plot(p_target_world[0], p_target_world[1], "r*", markersize=14, label="Target (Red Truck)")
    axs[0, 0].add_patch(plt.Circle((p_target_world[0], p_target_world[1]), 3.0, color="r", fill=False, linestyle="--", label="Arrival Radius (3m)"))
    if len(log_drone_x) > 18:
        axs[0, 0].plot(log_drone_x[12:19], log_drone_y[12:19], "g-o", linewidth=3, label="Occlusion Zone (Tree)")
    axs[0, 0].set_title("1. Bird's Eye View 2D Trajectory")
    axs[0, 0].set_xlabel("World X (m)")
    axs[0, 0].set_ylabel("World Y (m)")
    axs[0, 0].legend(loc="upper left")
    axs[0, 0].grid(True, linestyle=":", alpha=0.6)
    axs[0, 0].axis("equal")

    # Plot 2: Relative Target Distance vs Time
    axs[0, 1].plot(log_time, log_goal_dist, "purple", linewidth=2.5, label="Estimated Distance (Tracker)")
    axs[0, 1].axhline(y=3.0, color="r", linestyle="--", label="Arrival Threshold (3.0m)")
    axs[0, 1].axvspan(12 * dt, 18 * dt, color="green", alpha=0.2, label="Tree Occlusion Window")
    axs[0, 1].set_title("2. Estimated Target Distance (goal_rel[3])")
    axs[0, 1].set_xlabel("Time (s)")
    axs[0, 1].set_ylabel("Distance (m)")
    axs[0, 1].legend(loc="upper right")
    axs[0, 1].grid(True, linestyle=":", alpha=0.6)

    # Plot 3: 2D Camera Bounding Box Tracking (u, v)
    axs[1, 0].plot(log_time, log_bbox_center_u, "b.-", label="BBox Center U (px)")
    axs[1, 0].plot(log_time, log_bbox_center_v, "c.-", label="BBox Center V (px)")
    axs[1, 0].axhline(y=cam.width / 2.0, color="b", linestyle=":", alpha=0.5, label="Optical Center cx (320px)")
    axs[1, 0].axhline(y=cam.height / 2.0, color="c", linestyle=":", alpha=0.5, label="Optical Center cy (240px)")
    axs[1, 0].axvspan(12 * dt, 18 * dt, color="green", alpha=0.2, label="Detector Occluded")
    axs[1, 0].set_title("3. 2D Camera Pixel Bounding Box (u, v)")
    axs[1, 0].set_xlabel("Time (s)")
    axs[1, 0].set_ylabel("Pixel Coordinate")
    axs[1, 0].legend(loc="upper right")
    axs[1, 0].grid(True, linestyle=":", alpha=0.6)

    # Plot 4: Tracker State Machine Timeline
    state_to_num = {"searching": 0, "occluded": 1, "tracking": 2, "arrived": 3}
    num_states = [state_to_num[s] for s in log_state]
    axs[1, 1].step(log_time, num_states, where="post", color="darkorange", linewidth=2.5)
    axs[1, 1].set_yticks([0, 1, 2, 3])
    axs[1, 1].set_yticklabels(["SEARCHING", "OCCLUDED", "TRACKING", "ARRIVED"])
    axs[1, 1].set_title("4. Target Tracker State Machine Transitions")
    axs[1, 1].set_xlabel("Time (s)")
    axs[1, 1].set_ylabel("State")
    axs[1, 1].grid(True, linestyle=":", alpha=0.6)

    plt.tight_layout()
    os.makedirs("artifacts", exist_ok=True)
    out_img = "artifacts/visual_goal_standalone_demo.png"
    plt.savefig(out_img, dpi=150)
    print(f"\n📊 Telemetry plot saved to: {out_img}")


if __name__ == "__main__":
    run_standalone_simulation()
